### ISSUE TITLE
Chart for Firewall Agent

### ISSUE THREAD

**Issue by jmarhee** [packet-labs/helm-charts#3]
Potential use-case for [Packet FW Agent project](https://github.com/packet-labs/packetnet-fw-agent)

Will need:

- [ ]  Credentials from existing `Secret` in `Env` key of template
- [ ]  Env value for `SEEK_TAG` and other options
- [ ]  `DaemonSet` for this

If we decide to proceed on this.

**Comment by displague** [comment]
Closing this because the FW Agent Project is scheduled for archival - https://github.com/packet-labs/packetnet-fw-agent/issues/20
